services:
  mongo:
    image: mongo:7.0
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - '5173:5173'

volumes:
  mongo_data:
